// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pitstop.Application.BaggageSetManagement.DataAccess;

namespace Pitstop.Application.BaggageSetManagement.Migrations
{
    [DbContext(typeof(BaggageSetManagementDBContext))]
    partial class BaggageSetManagementDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pitstop.Application.BaggageSetManagement.Model.BaggageSet", b =>
                {
                    b.Property<string>("ScheduledFlightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaggageClaimId");

                    b.Property<bool>("DeliveredToBaggageClaim");

                    b.Property<bool>("LoadedOnFlight");

                    b.HasKey("ScheduledFlightId");

                    b.ToTable("BaggageSet");
                });
#pragma warning restore 612, 618
        }
    }
}
